version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    depends_on:
      - pma
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1

  app:
    build: .
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - db

volumes:
  db_data:
